pool:
  vmImage: 'ubuntu-16.04'

container: 
  image: sysdiglabs/secure-inline-scan:latest  
  options: -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock

variables:
  imageName: 'alejandroregistry.azurecr.io/ms-ignite-sampleimg'
  tags: |
    3a4019a9a6fcba53072957cce22673e3c33865d5
steps:
- task: Docker@2
  displayName: Build image
  inputs:
    repository: $(imageName)
    command: build
    tags: $(tags)

- script: inline_scan analyze -s https://secure.sysdig.com -k $(secureApiKey) $(imageName):3a4019a9a6fcba53072957cce22673e3c33865d5
  displayName: Scan image

- task: Docker@2
  inputs:
    command: 'login'

- task: Docker@2
  inputs:
    command: 'push'
    tags: $(tags)
