on: [push]
name: DevOps_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Build image'
          run: docker build . --file Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/uns-sampleapp:latest

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Login to Azure container registry'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: 'Push image to Azure Registry'
          run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/uns-sampleapp:latest

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: msignitedemowebapp 
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/uns-sampleapp:latest
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: aci-uns-sampleapp
            location: 'west us'
