on: [push]
name: Secure_DevOps_Workflow

jobs:
    build-scan-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Build image'
          run: docker build . --file Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/s-sampleapp:latest

        - name: Scan image
          uses: sysdiglabs/scan-action@v3
          id: scan
          with:
            image-tag: "${{ secrets.REGISTRY_LOGIN_SERVER }}/s-sampleapp:latest"
            sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
            run-as-user: root
            input-type: docker-daemon 

        - uses: github/codeql-action/upload-sarif@v1
          if: ${{ always() }} 
          with:
            sarif_file: ${{ steps.scan.outputs.sarifReport }}

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Login to Azure container registry'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: 'Push image to Azure Registry'
          run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/s-sampleapp:latest

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            #dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            dns-name-label: msignitesecuredemowebapp${{ github.run_number }} 
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/s-sampleapp:latest
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: aci-s-sampleapp
            location: 'west us'
